from .test_general import TestServiceSectionInfoGeneral
from .test_local import TestServiceSectionInfoLocal
from .test_mapping import TestServiceSectionInfoMapping
from .test_static import TestServiceSectionInfoStatic
from .test_tag import TestServiceSectionInfoTag
